services:
  # Backend API Service
  - type: web
    name: gurgaon-sites
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: gurgaon-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
    healthCheckPath: /api/health

  # Frontend Service (if needed as separate service)
  - type: web
    name: gurgaon-flats
    env: static
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  - name: gurgaon-db
    databaseName: gurgaon
    user: gurgaon
    plan: free