services:
  # Backend API Service
  - type: web
    name: gurgaon-sites
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: ./deploy.sh
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: gurgaon-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
    healthCheckPath: /api/health
    autoDeploy: true

databases:
  - name: gurgaon-db
    databaseName: gurgaon
    user: gurgaon
    plan: free